In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.insert(0, module_path)

In [2]:
import api
import geo_utils
import json
import json_matlab
import numpy as np
import scipy.io as sio

In [ ]:
resps = api.queue_tile_processing(5, 2, refresh=True)

2017-03-30 13:00:24,645 MainProcess: Starting new HTTP connection (1): lcmap-test.cr.usgs.gov
2017-03-30 13:00:25,069 MainProcess: http://lcmap-test.cr.usgs.gov:80 "GET /changes/results/lcmap-pyccd:1.1.0/-1815585/3014805?refresh=true HTTP/1.1" 202 982
2017-03-30 13:00:25,079 MainProcess: Starting new HTTP connection (1): lcmap-test.cr.usgs.gov
2017-03-30 13:00:25,253 MainProcess: http://lcmap-test.cr.usgs.gov:80 "GET /changes/results/lcmap-pyccd:1.1.0/-1812585/3014805?refresh=true HTTP/1.1" 202 982
2017-03-30 13:00:25,263 MainProcess: Starting new HTTP connection (1): lcmap-test.cr.usgs.gov
2017-03-30 13:00:25,438 MainProcess: http://lcmap-test.cr.usgs.gov:80 "GET /changes/results/lcmap-pyccd:1.1.0/-1809585/3014805?refresh=true HTTP/1.1" 202 982
2017-03-30 13:00:25,448 MainProcess: Starting new HTTP connection (1): lcmap-test.cr.usgs.gov
2017-03-30 13:00:25,651 MainProcess: http://lcmap-test.cr.usgs.gov:80 "GET /changes/results/lcmap-pyccd:1.1.0/-1806585/3014805?refresh=true HTTP/1.1" 

In [4]:
len(resps)

2500

In [ ]:
out = r'D:\temp\TSFitmap'
json_matlab.run(out, 5, 2, 4)

In [8]:
geo_utils.extent_from_hv(5, 2)

(GeoExtent(x_min=-1815585, y_max=3014805, x_max=-1665585, y_min=2864805),
 GeoAffine(ul_x=-1815585, x_res=30, rot_1=0, ul_y=3014805, rot_2=0, y_res=-30))

In [8]:
resp = api.api_request(-1665685, 2864905)

In [9]:
resp

{u'algorithm': u'lcmap-pyccd:1.1.0',
 u'algorithm-available': True,
 u'inputs_url': u'http://lcmap-test.cr.usgs.gov:80/landsat/tiles?x=-1665685&y=2864905&acquired=1980-01-01/2015-12-31&ubid=LANDSAT_4/TM/cfmask&ubid=LANDSAT_4/TM/sr_band1&ubid=LANDSAT_4/TM/sr_band2&ubid=LANDSAT_4/TM/sr_band3&ubid=LANDSAT_4/TM/sr_band4&ubid=LANDSAT_4/TM/sr_band5&ubid=LANDSAT_4/TM/sr_band7&ubid=LANDSAT_4/TM/toa_band6&ubid=LANDSAT_5/TM/cfmask&ubid=LANDSAT_5/TM/sr_band1&ubid=LANDSAT_5/TM/sr_band2&ubid=LANDSAT_5/TM/sr_band3&ubid=LANDSAT_5/TM/sr_band4&ubid=LANDSAT_5/TM/sr_band5&ubid=LANDSAT_5/TM/sr_band7&ubid=LANDSAT_5/TM/toa_band6&ubid=LANDSAT_7/ETM/cfmask&ubid=LANDSAT_7/ETM/sr_band1&ubid=LANDSAT_7/ETM/sr_band2&ubid=LANDSAT_7/ETM/sr_band3&ubid=LANDSAT_7/ETM/sr_band4&ubid=LANDSAT_7/ETM/sr_band5&ubid=LANDSAT_7/ETM/sr_band7&ubid=LANDSAT_7/ETM/toa_band6',
 u'refresh': False,
 u'source-data-available': True,
 u'tile_update_requested': u'2017-03-28T20:02:57.059Z',
 u'tile_x': -1668585,
 u'tile_y': 2867805,
 u'x': -

In [6]:
api.api_request(-2220585, 1928535)

{u'algorithm': u'lcmap-pyccd:1.1.0',
 u'algorithm-available': True,
 u'inputs_md5': u'not implemented',
 u'inputs_url': u'http://lcmap-test.cr.usgs.gov:80/landsat/tiles?x=-2220585&y=1928535&acquired=1980-01-01/2015-12-31&ubid=LANDSAT_4/TM/cfmask&ubid=LANDSAT_4/TM/sr_band1&ubid=LANDSAT_4/TM/sr_band2&ubid=LANDSAT_4/TM/sr_band3&ubid=LANDSAT_4/TM/sr_band4&ubid=LANDSAT_4/TM/sr_band5&ubid=LANDSAT_4/TM/sr_band7&ubid=LANDSAT_4/TM/toa_band6&ubid=LANDSAT_5/TM/cfmask&ubid=LANDSAT_5/TM/sr_band1&ubid=LANDSAT_5/TM/sr_band2&ubid=LANDSAT_5/TM/sr_band3&ubid=LANDSAT_5/TM/sr_band4&ubid=LANDSAT_5/TM/sr_band5&ubid=LANDSAT_5/TM/sr_band7&ubid=LANDSAT_5/TM/toa_band6&ubid=LANDSAT_7/ETM/cfmask&ubid=LANDSAT_7/ETM/sr_band1&ubid=LANDSAT_7/ETM/sr_band2&ubid=LANDSAT_7/ETM/sr_band3&ubid=LANDSAT_7/ETM/sr_band4&ubid=LANDSAT_7/ETM/sr_band5&ubid=LANDSAT_7/ETM/sr_band7&ubid=LANDSAT_7/ETM/toa_band6',
 u'refresh': False,
 u'result': None,
 u'result_md5': None,
 u'result_ok': None,
 u'result_produced': None,
 u'source-data-a

In [3]:
json_matlab.worker((r'D:\lcmap\stuff', 5, 2, 1000))

MainProcess: working line: 1000
MainProcess: writing line: 1000, time: 816.440999985


In [12]:
ta = np.zeros(1, dtype=[('f1', 'i4', (2, 2)), ('f2', 'i4')])
tb = np.zeros(1, dtype=[('f1', 'i4', (2, 2)), ('f2', 'i4')])

In [13]:
ta[0]['f1'] = [[1, 1],
               [1, 1]]
ta[0]['f2'] = 1
tb[0]['f1'] = [[2, 2],
               [2, 2]]
tb[0]['f2'] = 2

In [17]:
tc = np.concatenate((ta, tb))
tc['f1']

array([[[1, 1],
        [1, 1]],

       [[2, 2],
        [2, 2]]])

In [19]:
def test_record():
    return np.zeros(1, dtype=[('pos', 'i4'), ('coefs', 'f4', (8, 7))])

file = r'D:\lcmap\stuff\test_out.mat'
big_arr = test_record()
big_arr['pos'] = 1

for i in range(1, 5000):
    arr = test_record()
    arr['pos'] = i
    big_arr = np.concatenate((big_arr, arr))
    
sio.savemat(file, {'rec_cg': big_arr})

In [3]:
ext, geo = geo_utils.extent_from_hv(5, 2)
print ext

GeoExtent(x_min=-1815585, y_max=3014805, x_max=-1665585, y_min=2864805)


In [5]:
coord = geo_utils.GeoCoordinate(x=-2220585, y=1928535)
geo_utils.geo_to_rowcol(geo, coord)

RowColumn(row=36209, column=-13500)

In [6]:
file = r'D:\lcmap\prods\coverage_.tif'
ds = geo_utils.get_raster_ds(file)
arr = ds.GetRasterBand(1).ReadAsArray()

In [13]:
np.where(arr == 0)

(array([  0,   0,   0, ..., 528, 528, 528], dtype=int64),
 array([1602, 1640, 1834, ..., 4997, 4998, 4999], dtype=int64))